[[redirects]]
  from = "/github"
  to = "https://github.com/LiterateInk"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/f5KNCnMWzB"

[[redirects]]
  from = "/pawnote"
  to = "https://github.com/LiterateInk/Pawnote"

[[redirects]]
  from = "/pawdirecte"
  to = "https://github.com/LiterateInk/Pawdirecte"

[[redirects]]
  from = "/crowous"
  to = "https://github.com/LiterateInk/Crowous"

[[redirects]]
  from = "/ezly"
  to = "https://github.com/LiterateInk/Ezly"
