[[redirects]]
  from = "/github"
  to = "https://github.com/LiterateInk"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/f5KNCnMWzB"

[[redirects]]
  from = "/pawnote/*"
  to = "https://github.com/LiterateInk/Pawnote/:splat"

[[redirects]]
  from = "/pawdirecte/*"
  to = "https://github.com/LiterateInk/Pawdirecte/:splat"

[[redirects]]
  from = "/crowous/*"
  to = "https://github.com/LiterateInk/Crowous/:splat"

[[redirects]]
  from = "/ezly/*"
  to = "https://github.com/LiterateInk/Ezly/:splat"
