[[redirects]]
  from = "/github/*"
  to = "https://github.com/LiterateInk/:splat"

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/f5KNCnMWzB"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/company/literateink"
